server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: APPLIANCE-SERVICE
          uri: lb://APPLIANCE-SERVICE
          predicates:
            - Path=/appliances/**
          filters:
            - name: CircuitBreaker
              args:
                name: APPLIANCE-SERVICE
                fallbackuri: forward:/applianceServiceFallBackMethod


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

